//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JwtTokenAuthenticationExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMaster
    {
        public int ClientKeyId { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
